frequency: 50

sensor_timeout: 0.2
two_d_mode: true
predict_to_current_time: false

# MyAGV.cpp의 TF 발행을 주석 처리했을 때, EKF가 유일한 발행자가 됩니다.
publish_tf: true 

map_frame: map
odom_frame: odom
base_link_frame: base_footprint
world_frame: odom

#######################################
# ODOM (MyAGV) - 속도 중심 설정
#######################################
odom0: /odom
odom0_config: [
  false, false, false,   # x, y, z (위치 데이터는 끕니다)
  false, false, false,   # roll, pitch, yaw
  true,  true,  false,   # vx, vy, vz (전진, 옆이동 속도만 사용)
  false, false, false,    # vroll, vpitch, vyaw (회전 속도 사용)
  false, false, false
]
odom0_differential: false
odom0_relative: false
# 임계값을 높여서 주행 중 데이터가 잘리지 않게 합니다.
odom0_twist_rejection_threshold: 2.0 

#######################################
# IMU - 각속도 중심 설정
#######################################
imu0: /imu/data_raw
imu0_config: [
  false, false, false,
  false, false, false, 
  false, false, false,
  false, false, true,    # vyaw (IMU의 각속도만 사용)
  false, false, false
]
imu0_differential: false
imu0_relative: false
imu0_twist_rejection_threshold: 2.0