%YAML:1.0
---
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 673.1591013157547, 0., 304.91358855575493, 0.,
       672.59831282050368, 238.28845807327582, 0., 0., 1. ]
dist_coeff: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 0.19517469786645364, -0.9273096603355484,
       -0.0071758182429687845, 0.0040488534333816576,
       0.80945828674349907 ]
